language: java
os: linux
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.CommandBox/artifacts/"
    - "$HOME/.CommandBox/server/"
env:
  global:
    - MODULE_ID=qb
  jobs:
    - ENGINE=adobe@2018
    - ENGINE=adobe@2016
    - ENGINE=lucee@5
before_install:
  - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox jq rsync
  - box install commandbox-cfformat
  - box install
before_script:
  - box server start name=qb cfengine=$ENGINE port=8500
script:
  - box testbox run runner='http://127.0.0.1:8500/tests/runner.cfm'
  - box run-script format:check
after_success:
  - box install commandbox-docbox,commandbox-semantic-release
  - box config set endpoints.forgebox.APIToken=${FORGEBOX_TOKEN}
  - box semantic-release
before_deploy:
  - # Set Current Version
  - TARGET_VERSION=`cat $TRAVIS_BUILD_DIR/box.json | jq '.version' -r`
  - box run-script generateAPIDocs
deploy:
  provider: s3
  on:
    branch: master
    condition: $ENGINE = adobe@2018
  skip_cleanup: true
  #AWS Credentials need to be set in Travis
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_SECRET
  bucket: "apidocs.ortussolutions.com"
  local_dir: $TRAVIS_BUILD_DIR/.tmp/apidocs
  upload_dir: coldbox-modules/$MODULE_ID/$TARGET_VERSION
  acl: public_read
notifications:
  email: false
