language: java
sudo: required
jdk:
  - oraclejdk8
cache:
  directories:
    - "$HOME/.CommandBox/artifacts/"
    - "$HOME/.CommandBox/server/"
env:
  matrix:
    - ENGINE=adobe@2018
    - ENGINE=adobe@2016
    - ENGINE=adobe@11
    - ENGINE=lucee@5
    - ENGINE=lucee@4.5
before_install:
  - curl -fsSl https://downloads.ortussolutions.com/debs/gpg | sudo apt-key add -
  - sudo echo "deb http://downloads.ortussolutions.com/debs/noarch /" | sudo tee -a /etc/apt/sources.list.d/commandbox.list
install:
  - sudo apt-get update && sudo apt-get --assume-yes install commandbox
  - box install
before_script:
  - box server start name=qb cfengine=$ENGINE port=8500
script:
  - box testbox run runner='http://127.0.0.1:8500/tests/runner.cfm'
after_success:
  - box install commandbox-semantic-release
  - box config set endpoints.forgebox.APIToken=${FORGEBOX_TOKEN}
  - box install commandbox-docbox
  - box run-script commitAPIDocs
  - box semantic-release
notifications:
  email: false
